# Generated by Django 5.0.3 on 2024-04-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('about', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('gbjoy', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='products/')),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('color', models.CharField(max_length=200)),
            ],
        ),
    ]
