# Generated by Django 5.0.3 on 2024-04-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('login', models.CharField(max_length=200)),
                ('parent', models.TextField()),
                ('coin', models.IntegerField()),
                ('day', models.IntegerField()),
            ],
        ),
    ]
