# Generated by Django 5.0.3 on 2024-04-08 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('last_name', models.TextField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('login', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('Backend', 'Backend'), ('Frontend', 'Frontend'), ('Starter', 'Starter'), ('Designer', 'Designer')], max_length=200)),
                ('day', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('day', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('room', models.CharField(max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.teacher')),
            ],
        ),
    ]
