# Generated by Django 5.0.3 on 2024-04-17 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_teacher_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='HomeWorks/')),
                ('text', models.TextField()),
                ('time', models.DateField(auto_now=True)),
                ('coin', models.IntegerField(null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.group')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.student')),
            ],
        ),
    ]
